SciROLabABW.Web/ViewModels/WesternBlot/WBIndex_VM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels
{
    public class WBIndex_VM
    {
        public string freeSearchStr { get; set; }
        public string searchUserName { get; set; }
        public string searchMethod { get; set; }
        public string searchExperimenter { get; set; }
        public string searchPrimaryAntibody { get; set; }
        public DateTime? dateAddedMinDate { get; set; }
        public DateTime? dateAddedMaxDate { get; set; }
        public DateTime? expMinDate { get; set; }
        public DateTime? expMaxDate { get; set; }

        public string CurrentSortOrder { get; set; }
        public string CurrentPageSize { get; set; }
        public string CurrentSearchType { get; set; }
        public string CurrentSearchStatMsg { get; set; }
        public string FreeSearchCurrentFilter { get; set; }
        public string UserNameCurrentFilter { get; set; }
        public string MethodCurrentFilter { get; set; }
        public string ExperimenterCurrentFilter { get; set; }
        public string PrimaryAntibodyCurrentFilter { get; set; }
        public DateTime? DateAddedCurrentMinDate { get; set; }
        public DateTime? DateAddedCurrentMaxDate { get; set; }
        public DateTime? ExperimentCurrentMinDate { get; set; }
        public DateTime? ExperimentCurrentMaxDate { get; set; }

        public PagedList.IPagedList<WBMainTableIndex_VM> WBMainTableIndex_VM { get; set; }

        List<string> wbSortListNames = new List<string> { 
                                       "Image ID, Descending", "Image ID, Ascending", 
                                       "User Name, Descending", "User Name, Ascending",
                                       "Image Name, Descending", "Image Name, Ascending",
                                       "Share Row Mode", 
                                       "Date Added, Descending", "Date Added, Ascending",
                                       "Method, Descending", "Method, Ascending",
                                       "Experiment ID, Descending", "Experiment ID, Ascending",
                                       "Experiment Date, Descending", "Experiment Date, Ascending",
                                       "Experimenter, Descending", "Experimenter, Ascending",
                                       "Primary Antibody Id, Descending", "Primary Antibody Id, Ascending", 
                                   };

        public List<string> GetWBSortList()
        {
            return wbSortListNames;
        }

        List<string> wbPageSizeList = new List<string> { "5", "10", "25" };

        public List<string> GetWBPageSizeList()
        {
            return wbPageSizeList;
        }

        public bool ClearFreeSearch(WBIndex_VM model)
        {
            model.freeSearchStr = null;
            return true;
        }

        public bool ClearAdvancedSearch(WBIndex_VM model)
        {
            model.searchUserName = null;
            model.searchMethod = null;
            model.searchExperimenter = null;
            model.searchPrimaryAntibody = null;
            model.dateAddedMinDate = null;
            model.dateAddedMaxDate = null;
            model.expMinDate = null;
            model.expMaxDate = null;
            return true;
        }

        public bool ClearSearch(WBIndex_VM model)
        {
            ClearFreeSearch(model);
            ClearAdvancedSearch(model);
            return true;
        }
    }
}

SciROLabABW.Web/ViewModels/WesternBlot/WBReferenceCreateFile_VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels
{
    public class WBReferenceCreateFile_VM
    {
        public WBReferenceCreateFile_VM()
        {
            rowID = Guid.NewGuid();
            userName = HttpContext.Current.User.Identity.Name;
        }
        [Display(Name = "File: ")]
        [Required(ErrorMessage = "This field is required!")]
        public HttpPostedFileBase file { get; set; }
        public string link { get; set; }
        public string fullPath { get; set; }
        public long referenceID { get; set; }
        public string userName { get; set; }
        public System.Guid rowID { get; set; }
        public Nullable<System.Guid> mainTableID { get; set; }
        public string refLocation { get; set; }
    }
}

SciROLabABW.Web/ViewModels/WesternBlot/WBReferenceCreateURL_VM.cs
using SciROLabABW.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels
{
    public class WBReferenceCreateURL_VM
    {
        public WBReferenceCreateURL_VM()
        {
            rowID = Guid.NewGuid();
            userName = HttpContext.Current.User.Identity.Name;
        }
        [Display(Name = "URL: ")]
        [Required(ErrorMessage = "This field is required!")]
        [Url(ErrorMessage = "Please enter a valid url")]
        public string link { get; set; }
        public string fullPath { get; set; }
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long referenceID { get; set; }
        public string userName { get; set; }
        public System.Guid rowID { get; set; }
        public System.Guid mainTableID { get; set; }
        public string refLocation { get; set; }

        public virtual WBMainTable WBMainTable { get; set; }
    }
}

SciROLabABW.Web/ViewModels/WesternBlot/WBReferenceEditFile_VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels
{
    public class WBReferenceEditFile_VM
    {
        [Display(Name = "File: ")]
        [Required(ErrorMessage = "This field is required!")]
        public HttpPostedFileBase file { get; set; }
        public string link { get; set; }
        public string fullPath { get; set; }
        public long referenceID { get; set; }
        public string userName { get; set; }
        public System.Guid rowID { get; set; }
        public Nullable<System.Guid> mainTableID { get; set; }
        public string refLocation { get; set; }
    }
}

SciROLabABW.Web/ViewModels/WesternBlot/WBReferenceEditURL_VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels
{
    public class WBReferenceEditURL_VM
    {
        [Display(Name = "URL: ")]
        [Required(ErrorMessage = "This field is required!")]
        [Url(ErrorMessage = "Please enter a valid url")]
        public string link { get; set; }
        public string fullPath { get; set; }
        public long referenceID { get; set; }
        public string userName { get; set; }
        public System.Guid rowID { get; set; }
        public Nullable<System.Guid> mainTableID { get; set; }
        public string refLocation { get; set; }
    }
}

SciROLabABW.Web/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;

namespace SciROLabABW.Web.Controllers
{
    [Authorize]
    public class ImageController : BaseController
    {
    }
}

SciROLabABW.Web/Controllers/WesternBlotController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SciROLabABW.Web.Models;
using System.IO;
using SciROLabABW.Web.ViewModels;
using SciROLabABW.Web.GroupsUtilities;
using AutoMapper;
using System.Threading.Tasks;
using System.Web.Hosting;
using SciROLabABW.Web.Mappings;
using PagedList;
using Microsoft.AspNet.Identity;
using System.Linq.Expressions;
using SciROLabABW.Web.Authorization;
using SciROLabABW.Web.MethodsUtilities;
using SciROLabABW.Web.TeamsUtilities;
using SciROLabABW.Web.RowsUtilities;

namespace SciROLabABW.Web.Controllers
{
    [Authorize]
    public class WesternBlotController : BaseController
    {
        private SciROLabWebEntities db = new SciROLabWebEntities();

        // GET: WesternBlot
        public ActionResult Index(WBIndex_VM model, string wbSortOrder, int? page, 
                                  string pageSizeStr, string startSearch, 
                                  string clearSearch, string searchType)
        {
            bool searchState = false;

            if (!string.IsNullOrEmpty(clearSearch))
            {
                model.ClearSearch(model);
                Session["freeSearchStr"] = null;
            }

            if ((searchType == null) && (model.CurrentSearchType == null))
            {
                if (Session["searchType"] == null)
                {
                    Session["searchType"] = "freeSearch";
                }
                searchType = Session["searchType"].ToString();
                model.CurrentSearchType = Session["searchType"].ToString();
            }
            else if (searchType == null)
            {
                searchType = model.CurrentSearchType;
                Session["searchType"] = searchType;
            }
            else if (model.CurrentSearchType != searchType)
            {
                model.CurrentSearchType = searchType;
                Session["searchType"] = searchType;
            }

            // Set the sort parameters
            if (wbSortOrder != null)
            {
                model.CurrentSortOrder = wbSortOrder;
                Session["sortOrder"] = wbSortOrder;
            }
            else if (model.CurrentSortOrder != null)
            {
                wbSortOrder = model.CurrentSortOrder;
                Session["sortOrder"] = wbSortOrder;
            }
            else
            {
                if(Session["sortOrder"] == null)
                {
                    Session["sortOrder"] = "Image ID, Descending"; // Set to default value
                }
                wbSortOrder = Session["sortOrder"].ToString();
                model.CurrentSortOrder = wbSortOrder;
            }

            // Set pagination parameters
            if (pageSizeStr != null)
            {
                model.CurrentPageSize = pageSizeStr;
                Session["pageSizeStr"] = pageSizeStr;
            }
            else if (model.CurrentPageSize != null)
            {
                pageSizeStr = model.CurrentPageSize;
                Session["pageSizeStr"] = pageSizeStr;
            }
            
            else
            {
                if (Session["pageSizeStr"] == null)
                {
                    Session["pageSizeStr"] = 5; // Set to default value
                }
                pageSizeStr = Session["pageSizeStr"].ToString();
                model.CurrentPageSize = pageSizeStr;
            }           

            // Get all main table rows that the user has permission to view.
            var wbMainTable = Rows.getUserPermmitedRowsViewMainTable(db);

            // If there is something in search boxes, update the query according to this data 
            // Set the page to the first page in case of a new search
            // else use currrent info to update search fields to the value they were set to on the last change
            if ((!string.IsNullOrEmpty(model.freeSearchStr)) ||
                (!string.IsNullOrEmpty(model.searchUserName)) ||
                (!string.IsNullOrEmpty(model.searchMethod)) ||
                (!string.IsNullOrEmpty(model.searchExperimenter)) ||
                (!string.IsNullOrEmpty(model.searchPrimaryAntibody)) ||
                (model.dateAddedMinDate != null) ||
                (model.dateAddedMaxDate != null) ||
                (model.expMinDate != null) ||
                (model.expMaxDate != null))
            {
                page = 1;
            }
            else
            {
                model.freeSearchStr = model.FreeSearchCurrentFilter;
                model.searchUserName = model.UserNameCurrentFilter;
                model.searchMethod = model.MethodCurrentFilter;
                model.searchExperimenter = model.ExperimenterCurrentFilter;
                model.searchPrimaryAntibody = model.PrimaryAntibodyCurrentFilter;
                model.dateAddedMinDate = model.DateAddedCurrentMinDate;
                model.dateAddedMaxDate = model.DateAddedCurrentMaxDate;
                model.expMinDate = model.ExperimentCurrentMinDate;
                model.expMaxDate = model.ExperimentCurrentMaxDate;
            }

            if (searchType == "freeSearch")
            {
                model.ClearAdvancedSearch(model);
                // If user is pressing on search and the search box is empty - reset Session state
                if ((!string.IsNullOrEmpty(startSearch)) && (String.IsNullOrEmpty(model.freeSearchStr)))
                {
                    Session["freeSearchStr"] = null;
                }
                else if ((String.IsNullOrEmpty(model.freeSearchStr)) && (Session["freeSearchStr"] != null))
                {
                    model.freeSearchStr = Session["freeSearchStr"].ToString();
                }

                if (!String.IsNullOrEmpty(model.freeSearchStr))
                {
                    Session["freeSearchStr"] = model.freeSearchStr;
                    // TODO:2: still need to work on this one to make the code more readable using Lambada like I did with the 'ContainsOrExpression'!!!
                    wbMainTable = wbMainTable.Where(sl =>
                        sl.mainID.ToString().Contains(model.freeSearchStr.ToUpper()) ||
                        sl.userName.ToString().Contains(model.freeSearchStr.ToUpper()) ||
                        sl.experimentMethod.ToString().Contains(model.freeSearchStr.ToUpper()) ||
                        sl.experimentID.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.experimentInfo.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.performer.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.blockID.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.primaryAntibodyId.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.primaryAntibody.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.secondaryAntibody.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.membraneInfo.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.membraneID.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.blot.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.comments.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.text1.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.text2.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.text3.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.text4.Contains(model.freeSearchStr.ToUpper()) ||
                        sl.imageName.Contains(model.freeSearchStr.ToUpper()));

                    searchState = true;
                }
            }
            else if (searchType == "advancedSearch")
            {
                model.ClearFreeSearch(model);
                Session["freeSearchStr"] = null;

                if (!string.IsNullOrEmpty(model.searchUserName))
                {
                    wbMainTable = wbMainTable.Where(sl => sl.userName.ToString().Contains(model.searchUserName.ToUpper()));
                    searchState = true;
                }

                if (!string.IsNullOrEmpty(model.searchMethod))
                {
                    wbMainTable = wbMainTable.Where(sl => sl.experimentMethod.ToString().Contains(model.searchMethod.ToUpper()));
                    searchState = true;
                }

                if (!string.IsNullOrEmpty(model.searchExperimenter))
                {
                    wbMainTable = wbMainTable.Where(sl => sl.performer.ToString().Contains(model.searchExperimenter.ToUpper()));
                    searchState = true;
                }

                if (!string.IsNullOrEmpty(model.searchPrimaryAntibody))
                {
                    wbMainTable = wbMainTable.Where(sl => sl.primaryAntibody.ToString().Contains(model.searchPrimaryAntibody.ToUpper()));
                    searchState = true;
                }

                // Filter data according to min. and max. date
                if ((model.expMinDate != null) && (model.expMaxDate != null))
                {
                    wbMainTable = wbMainTable.Where(x => x.experimentDate <= model.expMaxDate && x.experimentDate >= model.expMinDate);
                    searchState = true;
                }

                // Filter data according to min. and max. date
                if ((model.dateAddedMinDate != null) && (model.dateAddedMaxDate != null))
                {
                    wbMainTable = wbMainTable.Where(x => x.dateAdded <= model.dateAddedMaxDate && x.dateAdded >= model.dateAddedMinDate);
                    searchState = true;
                }
            }            

            // Sort data according to the selected value
            switch (wbSortOrder)
            {

SciROLabABW.Web/Views/WesternBlot/EditMultiple.cshtml
@using PagedList.Mvc;
@using SciROLabABW.Web.CustomHtmlHelpers;
@model PagedList.PagedList<SciROLabABW.Web.ViewModels.WBMainTableEdit_VM>

<style type="text/css">
    .form-control {
        max-width: 100%;
    }

    #bottomContainer {
        clear: both;
        width: 100%;
        padding-top: 2em;
    }
</style>

<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

@{
    ViewBag.Title = "Edit Mode";
}

<h2>Edit Mode View</h2>

<div>
    @Html.ActionLink("Back to List", "Index") |
    <a href="" class="historyGoBack"> Go Back </a>
</div>

@using (Html.BeginForm("EditMultiple", "WesternBlot", FormMethod.Get,
       new { defaultbutton = "SubmitButton", id = "MainForm" }))
{
    <div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount.
        Maximum Items in Page: @Html.DropDownList("pageSizeStr", null, new { @onchange = "this.form.submit();", @class = "skipLeavePageValid" })
    </div>
    @*Note: if you change this one change also the one at the bottom of this page - TODO: find a better way to duplicate @Html.PagedListPager.*@
    @Html.PagedListPager(Model, page => Url.Action("EditMultiple", new
    {
        page,
        currentSortOrder = ViewBag.CurrentSortOrder,
        currentSearchText = ViewBag.CurrentSearchText,
        currentPageSize = ViewBag.CurrentPageSize,
    }))

    <div>
        @Html.Hidden("pageSize", ViewData["CurrentPageSize"] as string, new { @readonly = "readonly" })

        <div>
            <button type="submit" name="startSearch" id="SubmitButton" value="Search" class="btnCoral" title="Search">
                <i class="glyphicon glyphicon-search"></i>
            </button>
                @Html.TextBox("freeSearchStr", ViewBag.CurrentSearchText as string, new { @class = "searchBox skipLeavePageValid" }) 
                <strong class="text-warning">@ViewData["CurrentSearchStatMsg"]</strong>
        </div>
    </div>

    <div>@Html.Label("Sort By:") @Html.DropDownList("ListSortOrder", null, new { @onchange = "this.form.submit();", @class = "skipLeavePageValid" })</div>
}

@using (Html.BeginForm("EditMultiple", "WesternBlot", FormMethod.Post,
       new { defaultbutton = "SubmitButton", id = "postForm" }))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div id="errorMessage" style="color: #ff0000; padding: 10px; font-weight: bold;"></div>

    <hr class="hr-table-coral" />
    <div class="form-horizontal">
        @Html.EditorForModel(Model)
    </div>

    <input type="submit" value="Save" class="btn btnCoral btnRad30 submitBtnHistoryBack submitBtn" id="submitBtnId" name="submit" />
}

@*Note: if you change this one change also the one at the top of this page.*@
@Html.PagedListPager(Model, page => Url.Action("EditMultiple", new
    {
        page,
        currentSortOrder = ViewBag.CurrentSortOrder,
        currentSearchText = ViewBag.CurrentSearchText,
        currentPageSize = ViewBag.CurrentPageSize,
    }))

<div id="bottomContainer">
    @Html.ActionLink("Back to List", "Index") |
    <a href="" class="historyGoBack"> Go Back </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/App/FormPostAsyncReload.js"></script>
    <script src="~/Scripts/App/LeavePageValidation.js"></script>
    <script src="~/Scripts/App/ProgressAnimation.js"></script>
    <script src="~/Scripts/App/PageHistoryGoBack.js"></script>
    <script src="~/Scripts/App/ExperimentMethodSelector.js"></script>
    <script src="~/Scripts/App/WBSetMultipleControlImage.js"></script>
    <script src="~/Scripts/App/ImnstSetMultipleControlImage.js"></script>
    <script src="~/Scripts/App/SetDefaultKeyOnEnter.js"></script>
    <script src="~/Scripts/App/AutoComplete.js"></script>
}

SciROLabABW.Web/Views/WesternBlot/_ISRowDBEdit.cshtml
@model SciROLabABW.Web.ViewModels.WBMainTableEdit_VM

<div class="form-group">
    @Html.LabelFor(model => model.experimentMethod, htmlAttributes: new { @class = "col-md-2" })
    <div class="col-md-10" style="word-wrap: break-word;">
        @Html.DisplayFor(model => model.experimentMethod, new { htmlAttributes = new { @class = "form-control" } })
    </div>
    @Html.HiddenFor(model => model.experimentMethod)
</div>

<div class="form-group">
    @Html.LabelFor(model => model.experimentID, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.experimentID, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.experimentID, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.experimentDate, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.experimentDate, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.experimentDate, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.experimentInfo, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.experimentInfo, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.experimentInfo, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.performer, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.performer, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.performer, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.slideDate, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.slideDate, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.slideDate, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.blockID, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.blockID, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.blockID, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.primaryAntibodyId, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.primaryAntibodyId, new { htmlAttributes = new { @id = "primaryAntibodyId", @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.primaryAntibodyId, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.primaryAntibody, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.primaryAntibody, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.primaryAntibody, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.secondaryAntibody, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.secondaryAntibody, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.secondaryAntibody, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.comments, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        @Html.EditorFor(model => model.comments, new { htmlAttributes = new { @class = "form-control autoComplete" } })
        @Html.ValidationMessageFor(model => model.comments, "", new { @class = "text-danger" })
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.posControl, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <div class="checkbox">
            @Html.EditorFor(model => model.posControl, new { htmlAttributes = new { @id = "posCtrlImgCheckBox", data_url = @Url.Action("SetImnstControlImage", "WesternBlot"), data_id = Model.rowID } })
            @Html.ValidationMessageFor(model => model.posControl, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

<div class="form-group">
    @Html.LabelFor(model => model.negControl, htmlAttributes: new { @class = "control-label col-md-2" })
    <div class="col-md-10">
        <div class="checkbox">
            @Html.EditorFor(model => model.negControl, new { htmlAttributes = new { @id = "negCtrlImgCheckBox", data_url = @Url.Action("SetImnstControlImage", "WesternBlot"), data_id = Model.rowID } })
            @Html.ValidationMessageFor(model => model.negControl, "", new { @class = "text-danger" })
        </div>
    </div>
</div>

SciROLabABW.Web/Views/WesternBlot/_RefCreateFile.cshtml
@model SciROLabABW.Web.ViewModels.WBReferenceCreateFile_VM

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title" id="refModalLabel">Add new Reference</h4>
</div>

@using (Html.BeginForm("CreateReferenceFile", "WesternBlot", FormMethod.Post, new { enctype = "multipart/form-data", Id = "postForm" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-body">
        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            @Html.HiddenFor(model => model.mainTableID)
            <div style="height: 250px; overflow: auto; border: 1px solid coral;">
                <table class="table">
                    <tr>
                        <td>
                            @Html.DisplayNameFor(model => model.file)
                            @Html.TextBoxFor(model => model.file, new { type = "file", name = "docFile", id = "fileNameTextBox" })
                            @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button class="btn btnRad30" data-dismiss="modal">Cancel</button>
        <input type="submit" value="OK" class="btn btnCoral btnRad30" id="btnReferencesSubmit" name="submit" />
    </div>
}

@Scripts.Render("~/bundles/jqueryval")
@Scripts.Render("~/bundles/RefModalFormPost")
<script src="~/Scripts/App/ProgressAnimation.js"></script>
<script src="~/Scripts/App/FormPostAsyncReload.js"></script>
<script src="~/Scripts/jquery.form.js"></script>