SciROLabABW.Web/ViewModels/Groups/GroupCreate_VM.cs
using SciROLabABW.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels.Groups
{
    public class GroupCreate_VM
    {
        public GroupCreate_VM()
        {
            if (string.IsNullOrEmpty(Id))
            {
                Id = Guid.NewGuid().ToString();
            }
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string userId { get; set; }
        public string userName { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}

SciROLabABW.Web/ViewModels/Groups/GroupManageUsers_VM.cs
using SciROLabABW.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SciROLabABW.Web.ViewModels.Groups
{
    public class GroupManageUsers_VM
    {
        public GroupManageUsers_VM()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }

        public string GroupId { get; set; }
        public string GroupName { get; set; }
    
        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
        public IEnumerable<string> SelectedUsers { get; set; }
        public IEnumerable<SelectListItem> Users { get; set; }
    }
}

SciROLabABW.Web/ViewModels/Groups/GroupManage_VM.cs
using SciROLabABW.Web.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels.Groups
{
    public class GroupManage_VM
    {
        public GroupManage_VM()
        {
            this.AspNetUsers = new HashSet<AspNetUser>();
        }
    
        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        public string userId { get; set; }
        public string userName { get; set; }
        public string TeamId { get; set; }
        public string TeamName { get; set; }

        public virtual ICollection<AspNetUser> AspNetUsers { get; set; }
    }
}

SciROLabABW.Web/Controllers/GroupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SciROLabABW.Web.Models;
using SciROLabABW.Web.GroupsUtilities;
using SciROLabABW.Web.TeamsUtilities;
using System.Threading.Tasks;
using SciROLabABW.Web.ViewModels;
using SciROLabABW.Web.ViewModels.Groups;
using AutoMapper;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using System.Linq.Expressions;

namespace SciROLabABW.Web.Controllers
{
    [Authorize(Roles = "Owner, Admin")]
    public class GroupsController : BaseController
    {
        private SciROLabWebEntities db = new SciROLabWebEntities();

        // GET: Groups
        public ActionResult Index()
        {
            var permittedGroups = Groups.GetPermittedGroupsList(db);

            var groupList = Mapper.Map<List<SciROLabGroup>, List<GroupManage_VM>>(permittedGroups);
            Mapper.AssertConfigurationIsValid();

            return View(groupList);
        }

        // GET: UserGroups
        [OverrideAuthorization]
        [Authorize]
        public ActionResult UserGroups()
        {
            string usrName = User.Identity.GetUserName();
            var permittedGroups = Groups.GetUserGroups(db, usrName);

            var groupList = Mapper.Map<List<SciROLabGroup>, List<GroupManage_VM>>(permittedGroups);
            Mapper.AssertConfigurationIsValid();

            return PartialView("_UserGroups", groupList);
        }

        // GET: Groups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Groups/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(GroupCreate_VM groupCreate_VM)
        {
            SciROLabTeam team = Teams.GetUserTeam(db);
            if(team == null)
            {
                ViewBag.GroupExistsMessage = "User must be part of a team to be able to create a group.";
                return View(groupCreate_VM);
            }

            if (ModelState.IsValid)
            {
                var permittedGroups = Groups.GetPermittedGroupsList(db);
                var groupList = Mapper.Map<List<SciROLabGroup>, List<GroupManage_VM>>(permittedGroups);

                foreach (var grp in groupList)
                {
                    if (grp.Name == groupCreate_VM.Name)
                    {
                        ViewBag.GroupExistsMessage = "Group with the same name already exists! Please try another name.";
                        return View(groupCreate_VM);
                    }
                }
                // Add user's information to the row
                groupCreate_VM.userId = User.Identity.GetUserId(); 
                groupCreate_VM.userName = User.Identity.GetUserName();

                SciROLabGroup sciROLabGroup = Mapper.Map<SciROLabGroup>(groupCreate_VM); // Map view model items to domain model
                Mapper.AssertConfigurationIsValid();

                // Add team information to the row
                sciROLabGroup.TeamId = team.Id;
                sciROLabGroup.TeamName = team.Name;

                db.SciROLabGroups.Add(sciROLabGroup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(groupCreate_VM);
        }

        // GET: Groups/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SciROLabGroup sciROLabGroup = db.SciROLabGroups.Find(id);
            if (sciROLabGroup == null)
            {
                return HttpNotFound();
            }

            GroupManage_VM group = Mapper.Map<GroupManage_VM>(sciROLabGroup);
            Mapper.AssertConfigurationIsValid();

            return View(group);
        }

        // POST: Groups/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(GroupManage_VM groupManage_VM)
        {
            if (ModelState.IsValid)
            {
                SciROLabGroup sciROLabGroup = Mapper.Map<SciROLabGroup>(groupManage_VM); // Map view model items to domain model
                Mapper.AssertConfigurationIsValid();

                db.Entry(sciROLabGroup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(groupManage_VM);
        }

        // GET: Groups/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SciROLabGroup sciROLabGroup = db.SciROLabGroups.Find(id);
            if (sciROLabGroup == null)
            {
                return HttpNotFound();
            }

            GroupManage_VM group = Mapper.Map<GroupManage_VM>(sciROLabGroup);
            Mapper.AssertConfigurationIsValid();
            return View(group);
        }

        // POST: Groups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            SciROLabGroup sciROLabGroup = db.SciROLabGroups.Find(id);
            foreach (var user in sciROLabGroup.AspNetUsers.ToList())
            {
                sciROLabGroup.AspNetUsers.Remove(user);
            }

            db.SciROLabGroups.Remove(sciROLabGroup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult AddUsers(string groupId)
        {
            try
            {
                if (groupId == null)
                {
                    throw new InvalidOperationException("Error: Couldn't find any group!");
                }

                SciROLabGroup group = db.SciROLabGroups.Find(groupId);

                if (group == null)
                {
                    return HttpNotFound();
                }

                SciROLabTeam team = Teams.GetUserTeam(db);

                List<SelectListItem> listItems = new List<SelectListItem>();
                if (team != null)
                {
                    // Build a list of all users from current team that are not already in the current group
                    foreach (AspNetUser user in team.AspNetUsers)
                    {
                        if (!(Groups.IsUserInGroup(group, user.UserName)))
                        {
                            SelectListItem selectList = new SelectListItem()
                            {
                                Text = user.UserName,
                                Value = user.Id
                            };
                            listItems.Add(selectList);
                        }
                    }
                }

                var viewModel = new GroupManageUsers_VM
                {
                    GroupId = group.Id,
                    GroupName = group.Name,
                    Users = listItems
                };

                return View("GroupAddUsers", viewModel);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddUsers(GroupManageUsers_VM viewModel, IEnumerable<string> SelectedUsers)
        {
            try
            {
                SciROLabGroup sciROLabGroup = db.SciROLabGroups.Find(viewModel.GroupId);

                if (SelectedUsers != null)
                {
                    foreach (string strUser in SelectedUsers)
                    {
                        AspNetUser user = db.AspNetUsers.Find(strUser);
                        sciROLabGroup.AspNetUsers.Add(user);
                    }
                    db.SaveChanges();
                }
                
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpGet]
        public ActionResult DeleteUsers(string groupId)
        {
            try
            {
                if (groupId == null)
                {
                    throw new InvalidOperationException("Error: Couldn't find any group!");
                }

                SciROLabGroup group = db.SciROLabGroups.Find(groupId);
               
                if (group == null)
                {
                    return HttpNotFound();
                }

                // Build a list of all users that are in the current group
                List<SelectListItem> listItems = new List<SelectListItem>();
                foreach (AspNetUser user in group.AspNetUsers)
                {
                    SelectListItem selectList = new SelectListItem()
                    {
                        Text = user.UserName,
                        Value = user.Id
                    };
                    listItems.Add(selectList);
                }

                var viewModel = new GroupManageUsers_VM
                {
                    GroupId = group.Id,
                    GroupName = group.Name,
                    Users = listItems
                };

                return View("GroupDeleteUsers", viewModel);
            }
            catch (Exception ex)
            {
                Response.StatusCode = (int)HttpStatusCode.BadRequest;
                return Json(ex.Message, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]

SciROLabABW.Web/Views/Groups/Create.cshtml
@model SciROLabABW.Web.ViewModels.Groups.GroupCreate_VM

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create Group</h2>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                <div class="text-danger">@ViewBag.GroupExistsMessage</div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btnCoral btnRad30 submitBtn" id="submitBtnId" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    <script src="~/Scripts/App/LeavePageValidation.js"></script>
}

SciROLabABW.Web/Views/Groups/Delete.cshtml
@model SciROLabABW.Web.ViewModels.Groups.GroupManage_VM

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete Group</h2>
<h3>Are you sure you want to delete this?</h3>

<hr class="hr-table-coral" />
<div class="form-horizontal">
        <div class="row">
            <div class="col-md-3" style="word-wrap: break-word;">
                @Html.Label("Group Name:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.DisplayFor(model => model.Name)
                </dl>
            </div>
            <div class="col-md-3">
                @Html.Label("Users:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.Partial("_GroupUsersIndex", Model)
                </dl>
            </div>
        </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btnCoral btnRad30" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }

</div>

SciROLabABW.Web/Views/Groups/Edit.cshtml
@model SciROLabABW.Web.ViewModels.Groups.GroupManage_VM

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Group</h2>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.userName)
        @Html.HiddenFor(model => model.userId)
        @Html.HiddenFor(model => model.TeamId)
        @Html.HiddenFor(model => model.TeamName)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btnCoral btnRad30 submitBtn" id="submitBtnId" />
            </div>
        </div>
    </div>
}

<div>
    <a href="" class="historyGoBack"> Go Back </a>
</div>

@section Scripts {
<script src="~/Scripts/App/LeavePageValidation.js"></script>
<script src="~/Scripts/App/PageHistoryGoBack.js"></script>
}

SciROLabABW.Web/Views/Groups/GroupAddUsers.cshtml
@model SciROLabABW.Web.ViewModels.Groups.GroupManageUsers_VM

@{
    ViewBag.Title = "AddUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("AddUsers", "Groups"))
{
    @Html.AntiForgeryToken()

    <h2>Add Users to Group</h2>
    <div>
        @Html.HiddenFor(model => model.GroupId)
        <hr class="hr-table-coral" />
        <div class="row">
            <div class="col-md-3" style="word-wrap: break-word;">
                @Html.Label("Group Name:", htmlAttributes: new { @class = "control-label" })
                @Html.DisplayFor(model => model.GroupName)
            </div>
            <div class="col-md-9">
                @Html.Label("Users:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.ListBoxFor(model => model.SelectedUsers, Model.Users, new { size = 20, @style = "min-width: 500px;" })
                </dl>
            </div>            
        </div>
        <div>
            <input type="submit" value="Add" class="btn btnCoral btnRad30 submitBtn" name="submit" id="submitBtnId" /> |
            <a href="" class="historyGoBack"> Go Back </a>
        </div>
    </div>
}

@section Scripts {
<script src="~/Scripts/App/LeavePageValidation.js"></script>
<script src="~/Scripts/App/PageHistoryGoBack.js"></script>
}

SciROLabABW.Web/Views/Groups/GroupDeleteUsers.cshtml
@model SciROLabABW.Web.ViewModels.Groups.GroupManageUsers_VM

@{
    ViewBag.Title = "DeleteUsers";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm("DeleteUsers", "Groups"))
{
    @Html.AntiForgeryToken()

    <h2>Delete Users from Group</h2>
    <div>
        @Html.HiddenFor(model => model.GroupId)
        <hr class="hr-table-coral" />
        <div class="row">
            <div class="col-md-3" style="word-wrap: break-word;">
                @Html.Label("Group Name:", htmlAttributes: new { @class = "control-label" })
                @Html.DisplayFor(model => model.GroupName)
            </div>
            <div class="col-md-9">
                @Html.Label("Users:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.ListBoxFor(model => model.SelectedUsers, Model.Users, new { size = 20, @style = "min-width: 500px;" })
                </dl>
            </div>
        </div>
        <div>
            <input type="submit" value="Delete" class="btn btnCoral btnRad30 submitBtn" name="submit" id="submitBtnId" /> |
            <a href="" class="historyGoBack"> Go Back </a>
        </div>
      </div>
}

@section Scripts {
<script src="~/Scripts/App/LeavePageValidation.js"></script>
<script src="~/Scripts/App/PageHistoryGoBack.js"></script>
}

SciROLabABW.Web/Views/Groups/Index.cshtml
@model IEnumerable<SciROLabABW.Web.ViewModels.Groups.GroupManage_VM>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Groups Manager</h2>

<hr class="hr-table-coral" />
<div class="form-horizontal">
    @Html.ActionLink("Create New Group", "Create")
    @foreach (var item in Model)
    {
        <hr class="hr-table-coral" />

    <div class="row">
        <div class="col-md-3">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.Label("Group Name: ")
                    </dt>
                    <dd>
                        <div style="word-wrap: break-word;">
                            @Html.DisplayFor(model => item.Name)
                        </div>
                    </dd>

                    <dt>
                        @Html.Label("User Name: ")
                    </dt>
                    <dd>
                        <div style="word-wrap: break-word;">
                            @Html.DisplayFor(model => item.userName)
                        </div>
                    </dd>
                </dl>
        </div>

            <div class="col-md-3">
                @Html.Label("Users:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.Partial("_GroupUsersIndex", item)
                </dl>
                <div>
                    @Html.ActionLink("Add Users", "AddUsers", "Groups", new { groupId = item.Id }, null) |
                    @Html.ActionLink("Delete Users", "DeleteUsers", "Groups", new { groupId = item.Id }, null)
                </div>
            </div>
    </div>

    <div>
        @Html.ActionLink("Edit Group", "Edit", new { id = item.Id }) |
        @Html.ActionLink("Delete Group", "Delete", new { id = item.Id })
    </div>

    }

SciROLabABW.Web/Views/Groups/UserGroups.cshtml
@model IEnumerable<SciROLabABW.Web.ViewModels.Groups.GroupManage_VM>

@{
    ViewBag.Title = "My Groups";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>My Groups</h2>

<div class="form-horizontal">
    @foreach (var item in Model)
    {
        <hr class="hr-table-coral" />
        <div class="row">
            <div class="col-md-3" style="word-wrap: break-word;">
                @Html.Label("Group Name:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.DisplayFor(model => item.Name)
                </dl>
            </div>
            <div class="col-md-3">
                @Html.Label("Users:", htmlAttributes: new { @class = "control-label" })
                <dl class="dl-horizontal">
                    @Html.Partial("_GroupUsersIndex", item)
                </dl>
            </div>
        </div>
    }
</div>

SciROLabABW.Web/Views/Groups/_GroupUsersIndex.cshtml
@model SciROLabABW.Web.ViewModels.Groups.GroupManage_VM

<style type="text/css">
    .boxDiv {
        height: 250px;
        min-width: 500px;
        max-width: 500px;
        overflow: auto;
        border: 1px solid coral;
    }
</style>

<div class="boxDiv">    
    <table class="table">
        @foreach (var item in Model.AspNetUsers)
        {
            <tr>
                <td>
                    @Html.Name(item.UserName)
                </td>
            </tr>
        }
    </table>
</div>

SciROLabABW.Web/Views/Groups/_UserGroups.cshtml
@model IEnumerable<SciROLabABW.Web.ViewModels.Groups.GroupManage_VM>

<style>
    .form-control {
        max-width: 100%;
    }

    #bottomContainer {
        clear: both;
        width: 100%;
        padding-top: 2em;
    }

    #sortable div {
        margin: 3px 3px 3px 3px;
        padding: 0px;
        float: left;
        width: 400px;
        height: auto;
        overflow: hidden;
        text-overflow: ellipsis;
        white-space: nowrap;
        font-size: 1em;
        text-align: left;
    }

    .modal-body {
        max-height: calc(100vh - 210px);
        overflow-y: auto;
    }
</style>

<div class="modal-header" style="background-color: coral;">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4>My Groups</h4>
</div>
<div class="modal-body">
    <button class="btn btnRad30" data-dismiss="modal">Close</button>
    <div class="form-horizontal">
        @foreach (var item in Model)
        {
            <hr class="hr-table-coral" />
            <div class="row">
                <div class="col-md-3" style="word-wrap: break-word;">
                    @Html.Label("Group Name:", htmlAttributes: new { @class = "control-label" })
                    <dl class="dl-horizontal">
                        @Html.DisplayFor(model => item.Name)
                    </dl>
                </div>
                <div class="col-md-3">
                    @Html.Label("Users:", htmlAttributes: new { @class = "control-label" })
                    <dl class="dl-horizontal">
                        @Html.Partial("_GroupUsersIndex", item)
                    </dl>
                </div>
            </div>
        }
    </div>
</div>
<div class="modal-footer"> </div>