SciROLabABW.Web/ViewModels/Phrases/PhrasesIndex_VM.cs
using SciROLabABW.Web.ViewModels.Phrases;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels
{
    public class PhrasesIndex_VM
    {
        public PagedList.IPagedList<PhrasesTableIndex_VM> PhrasesTableIndex_VM { get; set; }

        List<string> phrasesSortListNames = new List<string> { 
                                           "Category, Descending", "Category, Ascending", 
                                           "Subject, Descending", "Subject, Ascending",
                                           "Phrase, Descending", "Phrase, Ascending",
                                           };

        public List<string> GetPhrasesSortList()
        {
            return phrasesSortListNames;
        }

        List<string> phrasesPageSizeList = new List<string> { "5", "10", "25", "50", "100" };

        public List<string> GetPhrasesPageSizeList()
        {
            return phrasesPageSizeList;
        }
    }
}

SciROLabABW.Web/ViewModels/Phrases/PhrasesTableCreate_VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels.Phrases
{
    public class PhrasesTableCreate_VM
    {
        public PhrasesTableCreate_VM()
        {
            Id = Guid.NewGuid();
            UserName = HttpContext.Current.User.Identity.Name;
        }

        public System.Guid Id { get; set; }
        [Display(Name = "Category: ")]
        public string Category { get; set; }
        [Display(Name = "Subject: ")]
        public string Subject { get; set; }
        [Required]
        [Display(Name = "Phrase: ")]
        [DataType(DataType.MultilineText)]
        public string Phrase { get; set; }
        [Display(Name = "User Name: ")]
        public string UserName { get; set; }
        public string UserId { get; set; }        
        public string TeamId { get; set; }
        public string TeamName { get; set; }
    }
}

SciROLabABW.Web/ViewModels/Phrases/PhrasesTableEdit_VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels.Phrases
{
    public class PhrasesTableEdit_VM
    {
        public System.Guid Id { get; set; }
        [Display(Name = "Category: ")]
        public string Category { get; set; }
        [Display(Name = "Subject: ")]
        public string Subject { get; set; }
        [Required]
        [Display(Name = "Phrase: ")]
        [DataType(DataType.MultilineText)]
        public string Phrase { get; set; }
        [Display(Name = "User Name: ")]
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string TeamId { get; set; }
        public string TeamName { get; set; }
    }
}

SciROLabABW.Web/ViewModels/Phrases/PhrasesTableIndex_VM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace SciROLabABW.Web.ViewModels.Phrases
{
    public class PhrasesTableIndex_VM
    {
        public System.Guid Id { get; set; }
        [Display(Name = "Category: ")]
        public string Category { get; set; }
        [Display(Name = "Subject: ")]
        public string Subject { get; set; }
        [Display(Name = "Phrase: ")]
        [DataType(DataType.MultilineText)]
        public string Phrase { get; set; }
        [Display(Name = "User Name: ")]
        public string UserName { get; set; }
        public string UserId { get; set; }
        public string TeamId { get; set; }
        public string TeamName { get; set; }
    }
}

SciROLabABW.Web/Controllers/PhrasesController.cs
using AutoMapper;
using SciROLabABW.Web.Models;
using SciROLabABW.Web.PhrasesUtilities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Net;
using System.Threading.Tasks;
using SciROLabABW.Web.ViewModels;
using SciROLabABW.Web.Authorization;
using System.Data.Entity;
using SciROLabABW.Web.ViewModels.Phrases;
using PagedList;

namespace SciROLabABW.Web.Controllers
{
    public class PhrasesController : BaseController
    {
        private SciROLabWebEntities db = new SciROLabWebEntities();

        // GET: Phrases
        public ActionResult Index(string listSortOrder, string currentSortOrder,
                                         string currentSearchText, string freeSearchStr,
                                         int? page, string pageSizeStr,
                                         string startSearch, string currentPageSize)
        {
            PhrasesIndex_VM pagingModel = new PhrasesIndex_VM();
            bool searchState = false;

            // Set the sort parameters
            if (listSortOrder != null)
            {
                currentSortOrder = listSortOrder;
                Session["phrasesSortOrder"] = listSortOrder;
            }
            else if (currentSortOrder != null)
            {
                listSortOrder = currentSortOrder;
                Session["phrasesSortOrder"] = listSortOrder;
            }
            else
            {
                if (Session["phrasesSortOrder"] == null)
                {
                    Session["phrasesSortOrder"] = "Category, Ascending"; // Set to default value
                }
                listSortOrder = Session["phrasesSortOrder"].ToString();
                currentSortOrder = listSortOrder;
            }

            // Set pagination parameters
            if (pageSizeStr != null)
            {
                currentPageSize = pageSizeStr;
                Session["phrasesPageSizeStr"] = pageSizeStr;
            }
            else if (currentPageSize != null)
            {
                pageSizeStr = currentPageSize;
                Session["phrasesPageSizeStr"] = pageSizeStr;
            }
            else
            {
                if (Session["phrasesPageSizeStr"] == null)
                {
                    Session["phrasesPageSizeStr"] = 25; // Set to default value
                }
                pageSizeStr = Session["phrasesPageSizeStr"].ToString();
                currentPageSize = pageSizeStr;
            }

            // Load from the DB server only permitted rows
            var permittedPhrases = Phrases.GetPermittedPhrases(db);

            // If there is something in search boxes, update the query according to this data 
            // Set the page to the first page in case of a new search
            // else use currrent info to update search fields to the value they were set to on the last change
            if (!string.IsNullOrEmpty(freeSearchStr))
            {
                page = 1;
            }
            else
            {
                freeSearchStr = currentSearchText;
            }

            // If user is pressing on search and the search box is empty - reset Session state
            if ((!string.IsNullOrEmpty(startSearch)) && (String.IsNullOrEmpty(freeSearchStr)))
            {
                Session["phrasesFreeSearchStr"] = null;
            }
            else if ((String.IsNullOrEmpty(freeSearchStr)) && (Session["phrasesFreeSearchStr"] != null))
            {
                freeSearchStr = Session["phrasesFreeSearchStr"].ToString();
            }

            if (!String.IsNullOrEmpty(freeSearchStr))
            {
                Session["phrasesFreeSearchStr"] = freeSearchStr;
                // TODO:2: still need to work on this one to make the code more readable using Lambada like I did with the 'ContainsOrExpression'!!!
                permittedPhrases = permittedPhrases.Where(sl =>
                    sl.Category.ToString().Contains(freeSearchStr.ToUpper()) ||
                    sl.Subject.ToString().Contains(freeSearchStr.ToUpper()) ||
                    sl.Phrase.ToString().Contains(freeSearchStr.ToUpper()) ||
                    sl.UserName.ToString().Contains(freeSearchStr.ToUpper()));
                if (permittedPhrases != null)
                {
                    searchState = true;
                }
                searchState = true;
            }

            // Sort data according to the selected value
            switch (listSortOrder)
            {
                case "Category, Ascending":
                default:
                    permittedPhrases = permittedPhrases.OrderBy(wb => wb.Category);
                    break;
                case "Category, Descending":
                    permittedPhrases = permittedPhrases.OrderByDescending(wb => wb.Category);
                    break;
                case "Subject, Ascending":
                    permittedPhrases = permittedPhrases.OrderBy(wb => wb.Subject);
                    break;
                case "Subject, Descending":
                    permittedPhrases = permittedPhrases.OrderByDescending(wb => wb.Subject);
                    break;
                case "Phrase, Ascending":
                    permittedPhrases = permittedPhrases.OrderBy(wb => wb.Phrase);
                    break;
                case "Phrase, Descending":
                    permittedPhrases = permittedPhrases.OrderByDescending(wb => wb.Phrase);
                    break;
                case "User Name, Ascending":
                    permittedPhrases = permittedPhrases.OrderBy(wb => wb.UserName);
                    break;
                case "User Name, Descending":
                    permittedPhrases = permittedPhrases.OrderByDescending(wb => wb.UserName);
                    break;    
            }

            // Set number of items per page according to page size selection
            int pageSize;
            switch (pageSizeStr)
            {
                case "5":
                default:
                    pageSize = 5;
                    break;
                case "10":
                    pageSize = 10;
                    break;
                case "15":
                    pageSize = 15;
                    break;
                case "25":
                    pageSize = 25;
                    break;
                case "50":
                    pageSize = 50;
                    break;
                case "100":
                    pageSize = 100;
                    break;
            }

            // Populate sort dropdownlist and set selected value
            ViewData["ListSortOrder"] = new SelectList(pagingModel.GetPhrasesSortList(), listSortOrder);
            // Populate page size dropdownlist and set selected value
            ViewData["pageSizeStr"] = new SelectList(pagingModel.GetPhrasesPageSizeList(), pageSizeStr);
            // Update page number with page value if not null, otherwise set to 1
            int pageNumber = (page ?? 1);

            ViewBag.CurrentSearchText = freeSearchStr;
            if (searchState == true)
            {
                ViewData["CurrentSearchStatMsg"] = "Search is ON";
            }
            else
            {
                ViewData["CurrentSearchStatMsg"] = "";
            }

            ViewBag.CurrentSortOrder = listSortOrder;
            ViewBag.CurrentPageSize = pageSizeStr;

            var phrasesTableIndex_VM_list = Mapper.Map<List<SciROLabPhrases>, List<PhrasesTableIndex_VM>>(permittedPhrases.ToList());
            Mapper.AssertConfigurationIsValid();

            var model = phrasesTableIndex_VM_list.ToPagedList(pageNumber, pageSize);
            return View(model);

        }

        // GET: Phrases/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Phrases/Create
        [HttpPost]
        public ActionResult Create(PhrasesTableCreate_VM phrases_VM)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var permittedPhrases = Phrases.GetPermittedPhrasesList(db);

                    // Add user's information to the row
                    phrases_VM.UserId = User.Identity.GetUserId();
                    phrases_VM.UserName = User.Identity.GetUserName();

                    SciROLabPhrases phrases = Mapper.Map<SciROLabPhrases>(phrases_VM);
                    Mapper.AssertConfigurationIsValid();

                    db.SciROLabPhrases.Add(phrases);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                return View();
            }
            catch (Exception)
            {
                return View();
            }
        }

        // GET: Phrases/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SciROLabPhrases phraseRow = db.SciROLabPhrases.Find(id);
            if (phraseRow == null)
            {
                return HttpNotFound();
            }

            PhrasesTableEdit_VM phrase = Mapper.Map<PhrasesTableEdit_VM>(phraseRow);
            Mapper.AssertConfigurationIsValid();

            return View(phrase);
        }

        // POST: Phrases/Edit/5
        [HttpPost]
        [EditDelAuthorize]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(PhrasesTableEdit_VM phrases_VM)
        {
            if (ModelState.IsValid)
            {
                SciROLabPhrases sciROLabPhrase = Mapper.Map<SciROLabPhrases>(phrases_VM); // Map view model items to domain model
                Mapper.AssertConfigurationIsValid();

                db.Entry(sciROLabPhrase).State = EntityState.Modified;
                db.SaveChanges();

SciROLabABW.Web/Views/Phrases/Create.cshtml
@model SciROLabABW.Web.ViewModels.Phrases.PhrasesTableCreate_VM

<style type="text/css">
    .form-control {
        max-width: 100%;
    }

    #bottomContainer {
        clear: both;
        width: 100%;
        padding-top: 2em;
    }
</style>

@{
    ViewBag.Title = "Add New Phrase";
}

<h2>Add New Phrase</h2>
<div>
    <a href="" class="mainListGoBack"> Back to List </a>
</div>

@using (Html.BeginForm("Create", "Phrases", FormMethod.Post, new { enctype = "multipart/form-data", Id = "postForm" }))
{
    @Html.AntiForgeryToken()

    <hr class="hr-table-coral" />

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-horizontal col-md-11">
        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10" style="word-wrap: break-word;">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10" style="word-wrap: break-word;">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phrase, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10" style="word-wrap: break-word;">
                @Html.EditorFor(model => model.Phrase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phrase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-top:2em;">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btnCoral btnRad30 submitBtnHistoryBack submitBtn" id="submitBtnId" name="submit" />
            </div>
        </div>
    </div>
}

<div id="bottomContainer">
    <hr class="hr-table-coral" />
    <a href="" class="mainListGoBack"> Back to List </a>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="~/Scripts/App/LeavePageValidation.js"></script>
    <script src="~/Scripts/App/ProgressAnimation.js"></script>
    <script src="~/Scripts/App/PageHistoryGoBack.js"></script>
    <script src="~/Scripts/App/PreventPostBackOnEnter.js"></script>
}

SciROLabABW.Web/Views/Phrases/Edit.cshtml
@model SciROLabABW.Web.ViewModels.Phrases.PhrasesTableEdit_VM

<style type="text/css">
    .form-control {
        max-width: 100%;
    }

    #bottomContainer {
        clear: both;
        width: 100%;
        padding-top: 2em;
    }
</style>

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit Method</h2>
<div>
    <a href="" class="mainListGoBack"> Back to List </a>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Category, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Category, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Category, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Subject, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Subject, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phrase, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phrase, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phrase, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "col-md-1" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.HiddenFor(model => model.UserName)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-10">
                <input type="submit" value="Save" class="btn btnCoral btnRad30 submitBtn" id="submitBtnId" />
            </div>
        </div>
    </div>
}

<div id="bottomContainer">
    <hr class="hr-table-coral" />
    <a href="" class="mainListGoBack"> Back to List </a>
</div>

@section Scripts {
    <script src="~/Scripts/App/LeavePageValidation.js"></script>
    <script src="~/Scripts/App/ProgressAnimation.js"></script>
    <script src="~/Scripts/App/PageHistoryGoBack.js"></script>
    <script src="~/Scripts/App/PreventPostBackOnEnter.js"></script>
}

SciROLabABW.Web/Views/Phrases/Index.cshtml
@using PagedList.Mvc;
@using SciROLabABW.Web.Authorization;
@model PagedList.PagedList<SciROLabABW.Web.ViewModels.Phrases.PhrasesTableIndex_VM>

<style type="text/css">
    .inline-container {
        display: inline-block;
        margin-right: 10px;
    }
</style>

@{
    ViewBag.Title = "Phrases Manager";
}

<h2>Phrases Manager</h2>
@using (Html.BeginForm("Index", "Phrases", FormMethod.Get,
       new { defaultbutton = "SubmitButton", id = "MainForm" }))
{
    <div>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount.
        Maximum Items in Page: @Html.DropDownList("pageSizeStr", null, new { @onchange = "this.form.submit();" })
    </div>
    @*Note: if you change this one change also the one at the bottom of this page - TODO: find a better way to duplicate @Html.PagedListPager.*@
    @Html.PagedListPager(Model, page => Url.Action("Index", new
    {
        page,
        currentSortOrder = ViewBag.CurrentSortOrder,
        currentSearchText = ViewBag.CurrentSearchText,
        currentPageSize = ViewBag.CurrentPageSize,
    }))

    <div>
        @Html.Hidden("pageSize", ViewData["CurrentPageSize"] as string, new { @readonly = "readonly" })

        <div>
            <button type="submit" name="startSearch" id="SubmitButton" value="Search" class="btnCoral" title="Search">
                <i class="glyphicon glyphicon-search"></i>
            </button>
            @Html.TextBox("freeSearchStr", ViewBag.CurrentSearchText as string)
            <strong class="text-warning">@ViewData["CurrentSearchStatMsg"]</strong>
        </div>
    </div>

    <div>@Html.Label("Sort By:") @Html.DropDownList("ListSortOrder", null, new { @onchange = "this.form.submit();" })</div>
<!-- References modal placeholder - check if i really need this one!!!-->
<div id='refModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='refModalContent'></div>
        </div>
    </div>

</div>

<hr class="hr-table-coral" />
    <div>
        <div class="inline-container"><h4>Phrases Table:</h4></div>
        <div class="inline-container">
            @Html.ActionLink("Add New", "Create", "Phrases", null, new { @class = "keepMainViewLocation", onclick = "ShowProgressModal()" })
        </div>
    </div>
<div class="inline-container"> <input type="checkbox" id="selecetAll" /><span> Select all rows (in current page)</span> </div>
<div class="dropdown inline-container">
    <button class="btn btn-default dropdown-toggle" data-toggle="dropdown"><span>Selected Rows Action </span><span class="caret"></span></button>
    <ul class="dropdown-menu" role="menu">
        <li><input type="button" class="btn btnLinkStyle" value="Delete selected rows" id="buttonDel" data-url=@Url.Action("DeleteMultiple", "Phrases")></li>
    </ul>
</div>

<div class="form-horizontal col-lg-offset-0">
    @for (var i = 0; i < Model.Count; i++)
    {
        <hr class="hr-table-coral" />
        if (AccessAuthorization.IsUserEditDelAutorized(User.Identity.Name, Model[i].UserName))
        {
            <input type="checkbox" name="selectRow" id="selectRow" value=@Model[i].Id /><span> Select row</span>
        }
        <div class="row">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model[i].Category)
                    </dt>
                    <dd>
                        <div style="word-wrap: break-word;">
                            @Html.DisplayFor(model => model[i].Category)
                        </div>
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model[i].Subject)
                    </dt>
                    <dd>
                        <div style="word-wrap: break-word;">
                            @Html.DisplayFor(model => model[i].Subject)
                        </div>
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model[i].Phrase)
                    </dt>
                    <dd>
                        <div style="word-wrap: break-word;">
                            @Html.DisplayFor(model => model[i].Phrase)
                        </div>
                    </dd>
                    <dt>
                        @Html.DisplayNameFor(model => model[i].UserName)
                    </dt>
                    <dd>
                        <div style="word-wrap: break-word;">
                            @Html.DisplayFor(model => model[i].UserName)
                        </div>
                    </dd>
                </dl>
            </div>
        </div>
        <div> 
            @if (AccessAuthorization.IsUserEditDelAutorized(User.Identity.Name, Model[i].UserName))
            {
                @Html.ActionLink("Edit ", "Edit", "Phrases", new { id = Model[i].Id }, new { @class = "keepMainViewLocation", onclick = "ShowProgressModal()" })
                @Html.ActionLink("| Delete", "Delete", "Phrases", new { @class = "modifyReferences", data_id = Model[i].Id, data_url = @Url.Action("Delete", "Phrases") })
            }
        </div>
    }
</div>
<hr class="hr-table-coral" />
}

@*Note: if you change this one change also the one at the top of this page.*@
@Html.PagedListPager(Model, page => Url.Action("Index", new
    {
        page,
        currentSortOrder = ViewBag.CurrentSortOrder,
        currentSearchText = ViewBag.CurrentSearchText,
        currentPageSize = ViewBag.CurrentPageSize,
    }))

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/RefModalFormGet")
    <script src="~/Scripts/App/MouseOverImageResize.js"></script>
    <script src="~/Scripts/jquery.form.js"></script>
    <script src="~/Scripts/App/ProgressAnimation.js"></script>
    <script src="~/Scripts/App/PageKeepScrollPosition.js"></script>
    <script src="~/Scripts/App/DeleteSelected.js"></script>
    <script src="~/Scripts/App/SelectAllCheckbox.js"></script>
}